### ISSUE TITLE
ModuleNotFoundError: No module named 'dsepruning'

### ISSUE THREAD

**Issue by lizhe-951202** [originlake/DSE#2]
I have downloaded the files and unzipped it.
Then according the references:
pip install -r requirement.txt
python setup.py build_ext --inplace
I finished the install.

But when I run the code, it showed  "ModuleNotFoundError: No module named 'dsepruning' "
What should I do? Why it appreared?
please…………

**Comment by originlake** [comment]
It's not setup as a pip package, you can include the dsepruning folder in your project

**Comment by lizhe-951202** [comment]
Thanks for your reply soooo much.
In addition, it usually take a long time to get the skeleton pruning results for high resolution images. Is this normal? Cuz I have planty of high resolution images need to be trained. How can upspeed it?
Thank you so much again.

**Comment by originlake** [comment]
It's already optimized with Cython and a better disk reconstruction structure. There could still be some other approaches like threading or GPU acceleration that could speed up the process, you are welcome to create PRs if you have better implementation. 
If you have multiple images to process, you can always process them in parallel. It's a straightforward way to improve the overall processing speed.

**Comment by lizhe-951202** [comment]
> It's already optimized with Cython and a better disk reconstruction structure. There could still be some other approaches like threading or GPU acceleration that could speed up the process, you are welcome to create PRs if you have better implementation. If you have multiple images to process, you can always process them in parallel. It's a straightforward way to improve the overall processing speed.

Many thanks.
Appeciate it. I am going to have a try.
