### ISSUE TITLE
 TypeError: expected str, bytes or os.PathLike object, not get_numpy_include

### ISSUE THREAD

**Issue by lphilomena** [originlake/DSE#7]
Hi, I got " TypeError: expected str, bytes or os.PathLike object, not get_numpy_include" when running the setup.py. Is this due to wrong python version? I have tried python 3.7, 3.8, 3.9, and 3.10, but all doesn't work. Could you please tell me how to fix this error?

**Comment by originlake** [comment]
The previous setup hack to get numpy dependency seems not working as expected. I've updated it, let me know if you still have issues.

**Comment by lphilomena** [comment]
@originlake Thank you very much! It works now with the new setup!
